#!/usr/bin/env python3
"""
Enhanced Symbol Table Analyzer for XV6-RISCV
Generates comprehensive symbol information with analysis
"""

import re
import subprocess
import sys
from collections import defaultdict
import argparse

class SymbolAnalyzer:
    def __init__(self, kernel_file):
        self.kernel_file = kernel_file
        self.symbols = []
        self.memory_layout = {}
        self.functions = {}
        self.variables = {}
        
    def parse_symbols(self):
        """Parse objdump output to extract symbol information"""
        try:
            # Get symbol table
            result = subprocess.run(['objdump', '-t', self.kernel_file], 
                                  capture_output=True, text=True, check=True)
            
            for line in result.stdout.split('\n'):
                if not line.strip() or 'SYMBOL TABLE' in line:
                    continue
                    
                parts = line.split()
                if len(parts) >= 6:
                    addr = parts[0]
                    flags = parts[1] if len(parts) > 1 else ''
                    section = parts[2] if len(parts) > 2 else ''
                    size = parts[4] if len(parts) > 4 else '0'
                    symbol_type = parts[3] if len(parts) > 3 else ''
                    name = parts[5] if len(parts) > 5 else ''
                    
                    symbol_info = {
                        'address': addr,
                        'size': size,
                        'type': symbol_type,
                        'name': name,
                        'section': section,
                        'flags': flags
                    }
                    
                    self.symbols.append(symbol_info)
                    
                    # Categorize symbols
                    if symbol_type in ['T', 't']:
                        self.functions[name] = symbol_info
                    elif symbol_type in ['B', 'b', 'D', 'd']:
                        self.variables[name] = symbol_info
                        
        except subprocess.CalledProcessError as e:
            print(f"Error running objdump: {e}")
            sys.exit(1)
    
    def get_memory_layout(self):
        """Get section headers and memory layout"""
        try:
            result = subprocess.run(['objdump', '-h', self.kernel_file],
                                  capture_output=True, text=True, check=True)
            
            for line in result.stdout.split('\n'):
                if re.match(r'^\s*\d+\s+\.', line):
                    parts = line.split()
                    if len(parts) >= 7:
                        section_name = parts[1]
                        size = parts[2]
                        vma = parts[3]
                        lma = parts[4]
                        self.memory_layout[section_name] = {
                            'size': size,
                            'vma': vma,
                            'lma': lma
                        }
                        
        except subprocess.CalledProcessError as e:
            print(f"Error getting memory layout: {e}")
    
    def analyze_function_sizes(self):
        """Analyze function sizes and find largest/smallest"""
        func_sizes = []
        for name, info in self.functions.items():
            try:
                size = int(info['size'], 16) if info['size'] != '0' else 0
                func_sizes.append((name, size))
            except ValueError:
                continue
                
        func_sizes.sort(key=lambda x: x[1], reverse=True)
        return func_sizes
    
    def find_symbol_by_address(self, address):
        """Find symbol at given address"""
        addr_int = int(address, 16)
        for symbol in self.symbols:
            sym_addr = int(symbol['address'], 16)
            sym_size = int(symbol['size'], 16) if symbol['size'] != '0' else 1
            if sym_addr <= addr_int < sym_addr + sym_size:
                return symbol
        return None
    
    def generate_enhanced_report(self, output_file):
        """Generate comprehensive symbol report"""
        with open(output_file, 'w') as f:
            f.write("# XV6-RISCV Enhanced Symbol Analysis Report\n")
            f.write(f"# Kernel: {self.kernel_file}\n")
            f.write(f"# Generated by SymbolAnalyzer\n\n")
            
            # Memory layout
            f.write("=== MEMORY LAYOUT ===\n")
            for section, info in self.memory_layout.items():
                f.write(f"{section:15} VMA: {info['vma']:16} Size: {info['size']:8}\n")
            f.write("\n")
            
            # Function analysis
            f.write("=== FUNCTION ANALYSIS ===\n")
            func_sizes = self.analyze_function_sizes()
            f.write(f"Total functions: {len(self.functions)}\n")
            
            if func_sizes:
                f.write(f"Largest function: {func_sizes[0][0]} ({func_sizes[0][1]} bytes)\n")
                f.write(f"Smallest function: {func_sizes[-1][0]} ({func_sizes[-1][1]} bytes)\n")
                
                f.write("\nTop 10 largest functions:\n")
                for name, size in func_sizes[:10]:
                    f.write(f"  {name:30} {size:6} bytes\n")
            f.write("\n")
            
            # All symbols sorted by address
            f.write("=== COMPLETE SYMBOL TABLE ===\n")
            f.write("Address          Size     Type Name\n")
            f.write("-" * 60 + "\n")
            
            sorted_symbols = sorted(self.symbols, key=lambda x: int(x['address'], 16))
            for symbol in sorted_symbols:
                f.write(f"{symbol['address']:16} {symbol['size']:8} {symbol['type']:4} {symbol['name']}\n")
            
            # Statistics
            f.write(f"\n=== STATISTICS ===\n")
            f.write(f"Total symbols: {len(self.symbols)}\n")
            f.write(f"Functions: {len(self.functions)}\n")
            f.write(f"Variables: {len(self.variables)}\n")
            
            # Symbol type breakdown
            type_count = defaultdict(int)
            for symbol in self.symbols:
                type_count[symbol['type']] += 1
            
            f.write(f"\nSymbol type breakdown:\n")
            for sym_type, count in sorted(type_count.items()):
                f.write(f"  {sym_type}: {count}\n")

def main():
    parser = argparse.ArgumentParser(description='Analyze XV6 kernel symbols')
    parser.add_argument('kernel', help='Path to kernel binary')
    parser.add_argument('-o', '--output', default='kernel-analysis.sym',
                       help='Output file for analysis report')
    
    args = parser.parse_args()
    
    analyzer = SymbolAnalyzer(args.kernel)
    analyzer.parse_symbols()
    analyzer.get_memory_layout()
    analyzer.generate_enhanced_report(args.output)
    
    print(f"Enhanced symbol analysis written to: {args.output}")

if __name__ == '__main__':
    main()